# Generated by Django 4.2.16 on 2024-12-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('evento', models.CharField(max_length=100)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant', models.CharField(blank=True, max_length=50, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
